version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-controle-financeiro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: controle_financeiro
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot123"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: app-controle-financeiro
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-controle-financeiro:3306/controle_financeiro?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  mysql_data: