version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-controle-financeiro
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app-controle-financeiro
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:

