spring.datasource.driver-class-name=com.mysql.jdbc.Driver
// esse comando é o driver de conecção.
spring.datasource.url=jdbc:mysql://localhost:3306/controle_finaceiro?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
//cria o banco de dados caso não exista. altere o nome do banco de dados.
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
atualiza sempre que criar tabelas.
spring.jpa.show-sql=true
//comandos sql aparecerão no terminal.spring.application.name=SistemaDeControleFinanceiro
