spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

admin.password=${ADMIN_PASSWORD}